FROM dase123/udlaia-stats:authservice

USER root
RUN apt-get update && apt-get install -y --no-install-recommends bash netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

COPY docker/entrypoint_auth.sh /app/entrypoint.sh

# Dar permisos
RUN chmod +x /app/entrypoint.sh

# Establecer entrypoint definitivo
ENTRYPOINT ["/app/entrypoint.sh"]
